-- Generated by lakehouse.agent (heuristic): low cardinality
select * from {{ ref('fct_daily_zone_trips') }} where cast("borough" as varchar) not in ('Manhattan', 'Queens', 'Brooklyn', 'Bronx', 'Staten Island', 'Unknown', 'N/A', 'EWR')
