-- Generated by lakehouse.agent (heuristic): low cardinality
select * from {{ ref('stg_yellow_trips') }} where cast("payment_method" as varchar) not in ('credit_card', 'cash', 'other', 'dispute', 'no_charge')
