-- Generated by lakehouse.agent (heuristic): low cardinality
select * from {{ ref('dim_zones') }} where cast("borough" as varchar) not in ('Queens', 'Manhattan', 'Brooklyn', 'Bronx', 'Staten Island', 'Unknown', 'EWR', 'N/A')
